# In this script, I'll train up the model.
# I'll generate a series of videos with random noise confined within a sample brightness range (I can use a simple gaussian distribution). Then I'll add glare in.
# I can track where I add the glare so I can determine what a perfect mask would look like. That way, I can provide really good feedback about what the mask should be.
from sklearn import neural_network

# I'll need some function to compare the mask generated by the neural network and the ideal mask.
# I want to ensure the maximum brightness whilst also removing hotspots.
def generate_sample_video(id):
    # according to the specifications I laid out, I'll create a piece of sample data.
    # id will be a sequential identifier for the video generated. I'll use this id both as a seed for any randomness, and for the name of the video
    # I'll create both a video and an "optimal" mask, both of which will have the same id
    # I may need to create a mask object or datatype.

    # True if no issues while generating, else false.
    return True

def train_model():
    # I'll need to setup the model, I'm thinking the number of input and output neurons will be the number of pixels of the input video
    # I'm not sure what I'll do for the hidden layer, perhaps the number of hidden neurons will be the magnitude of the range of brightness
    # Not sure if I want an activation function, if I do I'm not sure which I should use. I need to consider the goal

    pass

def create_dataset(n):
    '''
    I'll create the dataset using the sample_video function.
    n is the number of videos to generate
    I'll split the dataset into the training and testing data, I'll use a standard 80% to train and 20% to test
    '''
    
    pass

def create_model():
    pass