# In this script, I'll train up the model.

# Import either pytorch or tensorflow (I'll need to determine which is best for this scenario, PyTorch's Dataset class could be a useful tool to consider)

# I'll need some function to compare the mask generated by the neural network and the ideal mask.
# I want to ensure the maximum brightness whilst also removing hotspots.

def evaluate():
    # Simple function to evaluate the model
    pass

def train_model():
    # I can use tqdm to create progress bars for the training loops
    pass

def create_dataset(n):
    '''
    I'll create the dataset using the sample_video function.
    n is the number of videos to generate
    I'll split the dataset into the training and testing data, I'll use a standard 80% to train and 20% to test
    '''
    pass

# May also need a losses file